name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libclamav-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  integration:
    name: integration
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libclamav-dev clamav-freshclam
    - name: Disable apparmor
      run: sudo apparmor_parser -R /etc/apparmor.d/usr.bin.freshclam
    - name: Fetch database
      run: freshclam -F --datadir=$PWD/tmp -l $PWD/tmp/freshclam.log
    - name: Run tests
      run: CLAMAV_PATH=$PWD/tmp cargo test -- --nocapture --ignored

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: clippy
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libclamav-dev
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --all-targets -- --deny warnings

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run cargo fmt
      run: cargo fmt -- --check
